export type Lang = "en" | "zh";
export type Bi = { en: string; zh: string };

export type Era =
  | "bronze-iron"
  | "classical"
  | "pax-romana"
  | "late-antiquity"
  | "early-medieval"
  | "high-medieval"
  | "crisis-renaissance"
  | "early-modern"
  | "modern";

export type Century = {
  id: string;
  label: Bi;
  romanCentury: string;
  yearRange: string;
  era: Era;
  theme: Bi;
  themeShort: Bi;
  region: Bi;
  body: Bi;
  events: { y: string; en: string; zh: string }[];
  figures: { en: string; zh: string }[];
  invented: Bi;
  ended: Bi;
  legacy: Bi;
  color: string;
};

export const ERAS: Record<Era, { en: string; zh: string; color: string }> = {
  "bronze-iron": { en: "Bronze → Iron", zh: "青铜 → 铁器", color: "#c9a96e" },
  classical: { en: "Classical Age", zh: "古典时代", color: "#d4a85a" },
  "pax-romana": { en: "Pax Romana", zh: "罗马和平", color: "#d4a85a" },
  "late-antiquity": { en: "Late Antiquity", zh: "古典晚期", color: "#a18b6f" },
  "early-medieval": { en: "Early Medieval", zh: "中世纪早期", color: "#a18b6f" },
  "high-medieval": { en: "High Medieval", zh: "中世纪盛期", color: "#c9a96e" },
  "crisis-renaissance": { en: "Crisis & Renaissance", zh: "危机与复兴", color: "#a83232" },
  "early-modern": { en: "Early Modern", zh: "近代早期", color: "#d4a85a" },
  modern: { en: "Modern", zh: "现代", color: "#e8dccc" },
};

export const CENTURIES: Century[] = [
  {
    id: "bce-10",
    label: { en: "10th century BCE", zh: "公元前 10 世纪" },
    romanCentury: "X BCE",
    yearRange: "1000–901 BCE",
    era: "bronze-iron",
    theme: { en: "The Davidic Kingdom", zh: "大卫王朝" },
    themeShort: { en: "David & Solomon · the Hebrew kingdom forms", zh: "大卫与所罗门 · 希伯来王国成形" },
    region: { en: "Levant · Mediterranean", zh: "黎凡特 · 地中海" },
    body: {
      en: "Iron is replacing bronze along the eastern Mediterranean. Phoenicians push out trading colonies; in the Levant, David consolidates the twelve tribes and his son Solomon builds the First Temple in Jerusalem. The Zhou dynasty rules a still-feudal China. The century writes the prologue of monotheism — a theology that will outlast every empire on this list.",
      zh: "铁器正在地中海东岸取代青铜。腓尼基人扩张贸易殖民地；在黎凡特，大卫整合十二支派，所罗门在耶路撒冷建造第一圣殿。周朝统治着仍处于封建制下的中国。这个世纪写下了一神教的序言 —— 一种将比此后所有帝国都更长寿的神学。",
    },
    events: [
      { y: "≈ 1000", en: "David captures Jerusalem; unites the Hebrew tribes.", zh: "大卫攻占耶路撒冷，统一希伯来诸支派。" },
      { y: "≈ 970", en: "Solomon's reign begins; the First Temple is built.", zh: "所罗门即位，第一圣殿建成。" },
      { y: "≈ 950", en: "Phoenician maritime trade flourishes.", zh: "腓尼基海上贸易繁荣。" },
      { y: "≈ 930", en: "Hebrew kingdom splits into Israel and Judah.", zh: "希伯来王国分裂为以色列与犹大。" },
    ],
    figures: [
      { en: "David", zh: "大卫" },
      { en: "Solomon", zh: "所罗门" },
      { en: "Hiram of Tyre", zh: "泰尔王希兰" },
    ],
    invented: { en: "Monotheistic statecraft; alphabetic writing diffusing across the Mediterranean.", zh: "一神教国家治理；字母文字在地中海传播。" },
    ended: { en: "The chaos that followed the Bronze Age Collapse.", zh: "青铜时代崩溃之后的混乱。" },
    legacy: { en: "Founded a theology that would seed Judaism, Christianity, and Islam.", zh: "奠定了一种神学，日后衍生出犹太教、基督教与伊斯兰教。" },
    color: "#c9a96e",
  },
  {
    id: "bce-9",
    label: { en: "9th century BCE", zh: "公元前 9 世纪" },
    romanCentury: "IX BCE",
    yearRange: "900–801 BCE",
    era: "bronze-iron",
    theme: { en: "The Assyrian Empire", zh: "亚述帝国" },
    themeShort: { en: "The first imperial war machine", zh: "第一台帝国战争机器" },
    region: { en: "Mesopotamia · Anatolia · Levant", zh: "美索不达米亚 · 安纳托利亚 · 黎凡特" },
    body: {
      en: "The Neo-Assyrian Empire industrializes warfare. Iron weapons, professional siege engineers, organized cavalry, and a brutal policy of mass deportation create the first state designed for permanent expansion. Homer's epics may take their final shape in this century, on the other side of the Aegean. Two opposite cultural projects sit side by side: the empire by force, and the empire by story.",
      zh: "新亚述帝国把战争工业化。铁制武器、专业的攻城工程师、有组织的骑兵，加上残酷的大规模人口迁徙政策，造就了人类第一个为永续扩张而设计的国家。在爱琴海另一侧，荷马的史诗也许在这一世纪定型。两种相反的文化工程并存：以武力建立的帝国，与以故事建立的帝国。",
    },
    events: [
      { y: "883", en: "Ashurnasirpal II expands Assyria with mass deportations.", zh: "亚述纳西尔帕二世以大规模迁徙扩张亚述。" },
      { y: "≈ 850", en: "Homeric epics reach written form (traditional date).", zh: "荷马史诗成文（传统年代）。" },
      { y: "853", en: "Battle of Qarqar: largest known battle of antiquity to date.", zh: "卡卡尔之战：当时已知最大的古代会战。" },
      { y: "814", en: "Carthage founded by Phoenician settlers.", zh: "腓尼基移民建立迦太基。" },
    ],
    figures: [
      { en: "Ashurnasirpal II", zh: "亚述纳西尔帕二世" },
      { en: "Shalmaneser III", zh: "撒缦以色三世" },
      { en: "Homer (legendary)", zh: "荷马（传说）" },
    ],
    invented: { en: "Industrial warfare; imperial bureaucracy with deportation as policy.", zh: "工业化战争；以迁徙为政策的帝国官僚制。" },
    ended: { en: "The plurality of small Levantine kingdoms.", zh: "黎凡特小王国并立的格局。" },
    legacy: { en: "Set the template every later empire would either imitate or rebel against.", zh: "为后世所有帝国设定了或模仿、或反抗的模板。" },
    color: "#c9a96e",
  },
  {
    id: "bce-8",
    label: { en: "8th century BCE", zh: "公元前 8 世纪" },
    romanCentury: "VIII BCE",
    yearRange: "800–701 BCE",
    era: "bronze-iron",
    theme: { en: "The Greek City-State", zh: "古希腊城邦" },
    themeShort: { en: "Polis · alphabet · Olympics · Rome", zh: "城邦 · 字母 · 奥运 · 罗马建城" },
    region: { en: "Greek world · Italy · Israel", zh: "希腊世界 · 意大利 · 以色列" },
    body: {
      en: "Across the Greek peninsula, the polis emerges — small self-governing cities whose argument with themselves will eventually produce philosophy, democracy, and theatre. The Greek alphabet, borrowed from Phoenicia, gives literacy a portable substrate. Rome is founded (753 BCE, by tradition). In Israel, the prophetic tradition begins to speak truth to imperial power. The DNA of two civilizations — Greek and Roman — is laid down in one century.",
      zh: "在希腊半岛各处，城邦兴起 —— 一种小型自治城市，它与自身的辩论最终将催生哲学、民主与戏剧。希腊人借自腓尼基的字母，给识字提供了可携带的载体。罗马按传统建于公元前 753 年。在以色列，先知传统开始向帝国权力讲真话。两大文明 —— 希腊与罗马 —— 的 DNA 在这同一个世纪写下。",
    },
    events: [
      { y: "776", en: "First Olympic Games at Olympia.", zh: "首届奥林匹克运动会在奥林匹亚举行。" },
      { y: "753", en: "Traditional date of Rome's founding.", zh: "罗马传统建城年。" },
      { y: "≈ 750", en: "Greek alphabet adapted from Phoenician.", zh: "希腊字母改自腓尼基字母。" },
      { y: "≈ 720", en: "Hesiod composes Works and Days; Greek lyric tradition begins.", zh: "赫西俄德著《劳作与时日》；希腊抒情诗传统起步。" },
    ],
    figures: [
      { en: "Romulus (legendary)", zh: "罗慕路斯（传说）" },
      { en: "Hesiod", zh: "赫西俄德" },
      { en: "Isaiah", zh: "以赛亚" },
    ],
    invented: { en: "The polis · alphabetic literacy · Olympic competition.", zh: "城邦 · 字母识字 · 奥运赛事。" },
    ended: { en: "Aegean dark age that followed Mycenaean collapse.", zh: "迈锡尼崩溃后的爱琴海黑暗时代。" },
    legacy: { en: "Two world capitals — Athens and Rome — both begin here.", zh: "两个世界首都 —— 雅典与罗马 —— 都从这里开始。" },
    color: "#c9a96e",
  },
  {
    id: "bce-7",
    label: { en: "7th century BCE", zh: "公元前 7 世纪" },
    romanCentury: "VII BCE",
    yearRange: "700–601 BCE",
    era: "bronze-iron",
    theme: { en: "Neo-Babylon", zh: "新巴比伦" },
    themeShort: { en: "Babylon ascends · coinage invented", zh: "巴比伦崛起 · 货币诞生" },
    region: { en: "Mesopotamia · Lydia · Greece", zh: "美索不达米亚 · 吕底亚 · 希腊" },
    body: {
      en: "Assyria reaches its peak — and the seeds of its collapse. Babylon's revival absorbs Assyrian power. In Lydia, the first metal coins are struck — a quiet technological revolution that will make commerce and taxation legible. Athens drafts Draco's laws — harsh, but the principle that law should be written endures. Zoroaster, somewhere in Iran, conceives ethical dualism.",
      zh: "亚述抵达顶峰，也埋下崩溃的种子。新巴比伦的复兴吸收亚述的力量。在吕底亚，第一批金属硬币被铸出 —— 一场静默的技术革命，将让商业与税收变得可读。雅典颁布德拉古法 —— 严苛，但『法应当被写下』的原则就此长存。某地伊朗的琐罗亚斯德，构想出伦理二元论。",
    },
    events: [
      { y: "≈ 700", en: "Lydia mints the first coins.", zh: "吕底亚铸造首批硬币。" },
      { y: "626", en: "Babylon revolts against Assyria.", zh: "巴比伦反抗亚述。" },
      { y: "612", en: "Nineveh falls; Neo-Assyrian Empire ends.", zh: "尼尼微陷落；新亚述帝国终结。" },
      { y: "621", en: "Draco's law code at Athens.", zh: "雅典颁布德拉古法典。" },
    ],
    figures: [
      { en: "Nabopolassar", zh: "那波帕拉沙尔" },
      { en: "Draco", zh: "德拉古" },
      { en: "Zoroaster (Iran)", zh: "琐罗亚斯德（伊朗）" },
    ],
    invented: { en: "Coinage. Written civic law. Ethical dualism.", zh: "金属货币。成文公民法。伦理二元论。" },
    ended: { en: "Two centuries of Assyrian terror.", zh: "亚述恐怖统治的两个世纪。" },
    legacy: { en: "Money becomes a technology. Law becomes a text. Both still rule us.", zh: "货币成为技术。法律成为文本。今天我们仍被这两者所统治。" },
    color: "#c9a96e",
  },
  {
    id: "bce-6",
    label: { en: "6th century BCE", zh: "公元前 6 世纪" },
    romanCentury: "VI BCE",
    yearRange: "600–501 BCE",
    era: "classical",
    theme: { en: "The Persian Empire", zh: "波斯帝国" },
    themeShort: { en: "Axial Age · Persia · Buddha · Confucius", zh: "轴心时代 · 波斯 · 佛陀 · 孔子" },
    region: { en: "Persia · India · China · Greece", zh: "波斯 · 印度 · 中国 · 希腊" },
    body: {
      en: "The Axial Age. Within a single century, four civilizations independently discover ethics as a project of the individual conscience. In India, the Buddha teaches the four noble truths. In China, Confucius and Laozi compose the moral grammar of East Asia. In Greece, Thales asks what the world is made of. In Persia, Cyrus the Great founds the first multi-ethnic, religiously tolerant empire — the largest the world has yet seen.",
      zh: "轴心时代。在同一个世纪内，四大文明各自独立地把伦理发现为个人良知的工程。印度，佛陀讲授四圣谛。中国，孔子与老子写下东亚的道德语法。希腊，泰勒斯问『世界由什么构成』。波斯，居鲁士大帝建立第一个多民族、宗教宽容的帝国 —— 当时世界上最大的帝国。",
    },
    events: [
      { y: "≈ 563", en: "Birth of Siddhartha Gautama, the Buddha.", zh: "释迦牟尼诞生。" },
      { y: "551", en: "Birth of Confucius.", zh: "孔子诞生。" },
      { y: "550", en: "Cyrus the Great founds the Achaemenid Persian Empire.", zh: "居鲁士大帝建立阿契美尼德波斯帝国。" },
      { y: "≈ 585", en: "Thales of Miletus predicts a solar eclipse; philosophy begins.", zh: "米利都的泰勒斯预测日食；哲学起步。" },
      { y: "586", en: "First Temple in Jerusalem destroyed; Babylonian exile.", zh: "耶路撒冷第一圣殿被毁；巴比伦之囚开始。" },
    ],
    figures: [
      { en: "Cyrus the Great", zh: "居鲁士大帝" },
      { en: "The Buddha", zh: "佛陀" },
      { en: "Confucius", zh: "孔子" },
      { en: "Laozi", zh: "老子" },
      { en: "Thales of Miletus", zh: "米利都的泰勒斯" },
    ],
    invented: { en: "Universal ethics. Religious tolerance as imperial policy. Philosophy.", zh: "普世伦理。把宗教宽容作为帝国政策。哲学。" },
    ended: { en: "The age in which gods alone gave meaning to a life.", zh: "唯有神祇才赋予生命意义的时代。" },
    legacy: { en: "Every later religion and philosophy reaches back here for its tap root.", zh: "此后所有的宗教与哲学，都把根脉伸回这里。" },
    color: "#d4a85a",
  },
  {
    id: "bce-5",
    label: { en: "5th century BCE", zh: "公元前 5 世纪" },
    romanCentury: "V BCE",
    yearRange: "500–401 BCE",
    era: "classical",
    theme: { en: "The Athenian Golden Age", zh: "雅典黄金时代" },
    themeShort: { en: "Democracy · drama · history · medicine", zh: "民主 · 戏剧 · 史学 · 医学" },
    region: { en: "Greece · Persia · India · China", zh: "希腊 · 波斯 · 印度 · 中国" },
    body: {
      en: "A few thousand citizens on a rocky peninsula invent democracy, tragedy, history, medicine, and the rational dialogue. Pericles funds the Parthenon. Sophocles writes Oedipus. Herodotus invents history. Hippocrates separates medicine from magic. Socrates begins to teach. The century also contains the Persian Wars and the Peloponnesian War — the world-historical event of a free society defeating an empire, then destroying itself.",
      zh: "几千名公民在一座岩岛上的半岛，发明了民主、悲剧、史学、医学，以及理性的对话。伯里克利出资建造帕特农神庙。索福克勒斯写下《俄狄浦斯王》。希罗多德发明历史。希波克拉底把医学从巫术中分离。苏格拉底开始讲学。这同一个世纪，也包含了希波战争与伯罗奔尼撒战争 —— 一段世界史级的事件：自由社会击败帝国，然后自我毁灭。",
    },
    events: [
      { y: "508", en: "Athenian democracy reformed by Cleisthenes.", zh: "克利斯提尼改革，雅典民主成形。" },
      { y: "490", en: "Battle of Marathon: Athens defeats Persia.", zh: "马拉松战役：雅典击败波斯。" },
      { y: "480", en: "Thermopylae and Salamis: the second Persian invasion repelled.", zh: "温泉关与萨拉米斯：第二次波斯入侵被击退。" },
      { y: "447", en: "Construction of the Parthenon begins.", zh: "帕特农神庙开工。" },
      { y: "431", en: "Peloponnesian War begins; ends in Athens' defeat.", zh: "伯罗奔尼撒战争爆发；以雅典战败告终。" },
      { y: "399", en: "Socrates is executed by Athenian court.", zh: "苏格拉底被雅典法庭处死。" },
    ],
    figures: [
      { en: "Pericles", zh: "伯里克利" },
      { en: "Socrates", zh: "苏格拉底" },
      { en: "Herodotus", zh: "希罗多德" },
      { en: "Sophocles", zh: "索福克勒斯" },
      { en: "Hippocrates", zh: "希波克拉底" },
    ],
    invented: { en: "Democracy. Tragedy. History. Medicine. The examined life.", zh: "民主。悲剧。史学。医学。被审视的人生。" },
    ended: { en: "The unchallenged authority of priest, king, and oracle.", zh: "祭司、君王与神谕不容质疑的权威。" },
    legacy: { en: "Every democratic constitution descends from this one century.", zh: "此后所有民主宪法，都源自这一个世纪。" },
    color: "#d4a85a",
  },
  {
    id: "bce-4",
    label: { en: "4th century BCE", zh: "公元前 4 世纪" },
    romanCentury: "IV BCE",
    yearRange: "400–301 BCE",
    era: "classical",
    theme: { en: "Alexander the Great", zh: "亚历山大大帝" },
    themeShort: { en: "From Macedonia to the Indus — and Aristotle", zh: "从马其顿到印度河 —— 与亚里士多德" },
    region: { en: "Macedonia · Persia · India · China", zh: "马其顿 · 波斯 · 印度 · 中国" },
    body: {
      en: "A young Macedonian king, taught by Aristotle, marches from Greece to the Indus in eleven years and dies at thirty-two. His empire fragments, but the cultures he fused — Greek, Persian, Egyptian, Indian — produce the Hellenistic world: a single trade and intellectual space stretching from the Mediterranean to the Hindu Kush. Plato founds the Academy. Aristotle systematizes nature. In India, Chandragupta Maurya creates the subcontinent's first empire.",
      zh: "一位年轻的马其顿国王，受教于亚里士多德，十一年内从希腊行军至印度河，三十二岁即逝。他的帝国分裂，但他所融合的文化 —— 希腊、波斯、埃及、印度 —— 催生出希腊化世界：从地中海延伸到兴都库什山的单一贸易与思想空间。柏拉图创办学园。亚里士多德系统化自然。印度的旃陀罗笈多·孔雀，建立次大陆首个帝国。",
    },
    events: [
      { y: "387", en: "Plato founds the Academy in Athens.", zh: "柏拉图在雅典创办学园。" },
      { y: "335", en: "Aristotle founds the Lyceum.", zh: "亚里士多德创办吕克昂。" },
      { y: "334", en: "Alexander invades Persia.", zh: "亚历山大入侵波斯。" },
      { y: "323", en: "Alexander dies in Babylon; empire splits among the Diadochi.", zh: "亚历山大死于巴比伦；帝国被部将瓜分。" },
      { y: "322", en: "Chandragupta Maurya founds the Mauryan Empire.", zh: "旃陀罗笈多·孔雀建立孔雀王朝。" },
    ],
    figures: [
      { en: "Alexander the Great", zh: "亚历山大大帝" },
      { en: "Aristotle", zh: "亚里士多德" },
      { en: "Plato", zh: "柏拉图" },
      { en: "Chandragupta Maurya", zh: "旃陀罗笈多·孔雀" },
    ],
    invented: { en: "Multi-continental empire. The Hellenistic synthesis. Systematic philosophy.", zh: "跨大陆帝国。希腊化综合。系统哲学。" },
    ended: { en: "The provincialism of the Greek city-state.", zh: "希腊城邦的地方主义。" },
    legacy: { en: "A common cultural language — Greek — spans three continents.", zh: "一种共同的文化语言 —— 希腊语 —— 横跨三大陆。" },
    color: "#d4a85a",
  },
  {
    id: "bce-3",
    label: { en: "3rd century BCE", zh: "公元前 3 世纪" },
    romanCentury: "III BCE",
    yearRange: "300–201 BCE",
    era: "classical",
    theme: { en: "The Qin Unification", zh: "秦朝统一" },
    themeShort: { en: "China unified · Punic Wars · Ashoka", zh: "中国一统 · 布匿战争 · 阿育王" },
    region: { en: "China · Mediterranean · India", zh: "中国 · 地中海 · 印度" },
    body: {
      en: "Qin Shi Huang unifies the warring states of China in 221 BCE — standardizing script, weights, and the axle width of carts. The administrative apparatus he builds will, with revisions, outlast every dynasty for two thousand years. In the Mediterranean, Rome and Carthage fight three Punic Wars; Rome wins the first two this century. In India, Ashoka inherits the Mauryan Empire and turns to nonviolent Buddhism after a brutal war.",
      zh: "公元前 221 年，秦始皇统一中国战国诸邦 —— 书同文、车同轨、衡同度。他建立的行政体制，在历代调整后，将延续两千年。地中海，罗马与迦太基爆发三次布匿战争，本世纪罗马赢下前两次。印度，阿育王继承孔雀王朝，在血腥战争后皈依非暴力的佛教。",
    },
    events: [
      { y: "264", en: "First Punic War begins.", zh: "第一次布匿战争爆发。" },
      { y: "≈ 268", en: "Ashoka's reign begins in India.", zh: "印度阿育王即位。" },
      { y: "221", en: "Qin Shi Huang unifies China.", zh: "秦始皇统一中国。" },
      { y: "218", en: "Hannibal crosses the Alps.", zh: "汉尼拔翻越阿尔卑斯山。" },
      { y: "206", en: "Han dynasty founded after Qin collapses.", zh: "秦亡，汉朝建立。" },
    ],
    figures: [
      { en: "Qin Shi Huang", zh: "秦始皇" },
      { en: "Hannibal Barca", zh: "汉尼拔" },
      { en: "Ashoka", zh: "阿育王" },
      { en: "Liu Bang (Han Gaozu)", zh: "刘邦（汉高祖）" },
    ],
    invented: { en: "Centralized bureaucratic empire (China). Buddhism as state ethic.", zh: "中央集权官僚帝国（中国）。作为国家伦理的佛教。" },
    ended: { en: "China's Warring States period; Carthaginian supremacy at sea.", zh: "中国战国时代；迦太基的海上霸权。" },
    legacy: { en: "The Chinese state and the Roman state — civilizational templates — both lock in this century.", zh: "中国国家与罗马国家 —— 两种文明模板 —— 都在本世纪定型。" },
    color: "#d4a85a",
  },
  {
    id: "bce-2",
    label: { en: "2nd century BCE", zh: "公元前 2 世纪" },
    romanCentury: "II BCE",
    yearRange: "200–101 BCE",
    era: "classical",
    theme: { en: "Roman Expansion", zh: "罗马扩张" },
    themeShort: { en: "Mediterranean becomes a Roman lake", zh: "地中海变成罗马的内湖" },
    region: { en: "Rome · Greece · China · India", zh: "罗马 · 希腊 · 中国 · 印度" },
    body: {
      en: "Rome destroys Carthage (146 BCE) and conquers Greece in the same year. The Mediterranean becomes a single political space. In China, Emperor Wu of Han opens the Silk Road, linking the Mediterranean to the Pacific by camel and caravan. Two unrelated empires — Rome and Han — now indirectly trade silk for glass. A century earlier this was impossible; a century later it will be routine.",
      zh: "罗马摧毁迦太基（公元前 146 年），同年征服希腊。地中海成为一个统一政治空间。中国，汉武帝开通丝绸之路，以骆驼与商队把地中海与太平洋连起。两个互不相识的帝国 —— 罗马与汉 —— 已开始间接交换丝绸与玻璃。一世纪之前这是不可能的；一世纪之后这将是常态。" ,
    },
    events: [
      { y: "202", en: "Battle of Zama: Rome defeats Hannibal.", zh: "扎马战役：罗马击败汉尼拔。" },
      { y: "146", en: "Carthage destroyed. Corinth sacked. Greece becomes Roman.", zh: "迦太基被毁。科林斯陷落。希腊归罗马。" },
      { y: "141", en: "Han Emperor Wu ascends the throne.", zh: "汉武帝即位。" },
      { y: "138", en: "Zhang Qian sent west; the Silk Road opens.", zh: "张骞西使；丝绸之路开通。" },
    ],
    figures: [
      { en: "Scipio Africanus", zh: "西庇阿" },
      { en: "Emperor Wu of Han", zh: "汉武帝" },
      { en: "Zhang Qian", zh: "张骞" },
      { en: "Cato the Elder", zh: "老加图" },
    ],
    invented: { en: "Long-distance Eurasian trade. The military-republican Roman state.", zh: "欧亚远距离贸易。军事共和制的罗马国家。" },
    ended: { en: "A multipolar Mediterranean.", zh: "多极化的地中海。" },
    legacy: { en: "The first integrated Old World — a single market from Spain to Korea.", zh: "第一个一体化的旧大陆 —— 从西班牙到朝鲜的统一市场。" },
    color: "#d4a85a",
  },
  {
    id: "bce-1",
    label: { en: "1st century BCE", zh: "公元前 1 世纪" },
    romanCentury: "I BCE",
    yearRange: "100–1 BCE",
    era: "classical",
    theme: { en: "The Roman Empire", zh: "罗马帝国" },
    themeShort: { en: "Republic dies · Augustus is born", zh: "共和制覆灭 · 屋大维登场" },
    region: { en: "Rome · Egypt · Judea", zh: "罗马 · 埃及 · 犹地亚" },
    body: {
      en: "The Roman Republic collapses under its own success. Caesar crosses the Rubicon, is assassinated, and his adopted heir Octavian — soon Augustus — ends a century of civil war and inaugurates the Empire. Cleopatra ends with him. Virgil writes the Aeneid. Cicero perfects Latin prose. The Pax Romana that follows is one of the longest peaces in recorded history; the cost is that no one votes meaningfully again for fourteen hundred years.",
      zh: "罗马共和国在自身的成功中崩溃。凯撒渡过卢比孔河，遇刺，其养子屋大维 —— 不久之后的奥古斯都 —— 终结了一个世纪的内战，开创帝制。克莱奥帕特拉随之落幕。维吉尔写下《埃涅阿斯纪》。西塞罗使拉丁散文臻于完美。随之而来的罗马和平，是有记载历史上最长的和平之一；代价是此后一千四百年里，无人能真正投票。",
    },
    events: [
      { y: "49", en: "Caesar crosses the Rubicon.", zh: "凯撒渡过卢比孔河。" },
      { y: "44", en: "Caesar assassinated on the Ides of March.", zh: "凯撒于三月之望被刺。" },
      { y: "31", en: "Battle of Actium: Octavian defeats Antony and Cleopatra.", zh: "亚克兴海战：屋大维击败安东尼与克莱奥帕特拉。" },
      { y: "27", en: "Augustus founds the Roman Empire.", zh: "奥古斯都建立罗马帝国。" },
      { y: "≈ 19", en: "Virgil completes the Aeneid.", zh: "维吉尔完成《埃涅阿斯纪》。" },
    ],
    figures: [
      { en: "Julius Caesar", zh: "凯撒" },
      { en: "Augustus", zh: "奥古斯都" },
      { en: "Cleopatra VII", zh: "克莱奥帕特拉七世" },
      { en: "Cicero", zh: "西塞罗" },
      { en: "Virgil", zh: "维吉尔" },
    ],
    invented: { en: "The principate; imperial dynasty as the default European political form.", zh: "元首制；以帝国王朝作为欧洲默认的政治形态。" },
    ended: { en: "The Roman Republic and the Hellenistic kingdoms.", zh: "罗马共和与希腊化王国。" },
    legacy: { en: "The political vocabulary — emperor, senate, prince, dictator — is set.", zh: "政治词汇 —— 皇帝、元老院、君侯、独裁者 —— 就此定型。" },
    color: "#d4a85a",
  },
  {
    id: "ce-1",
    label: { en: "1st century CE", zh: "公元 1 世纪" },
    romanCentury: "I",
    yearRange: "1–100 CE",
    era: "pax-romana",
    theme: { en: "The Birth of Christianity", zh: "基督教诞生" },
    themeShort: { en: "A small Jewish sect, a vast Roman peace", zh: "罗马治下，一个犹太小教派" },
    region: { en: "Judea · Rome · China", zh: "犹地亚 · 罗马 · 中国" },
    body: {
      en: "A Galilean carpenter is crucified by a Roman governor; his followers, against every reasonable prediction, take over the empire within three centuries. The Pax Romana makes their roads. Paul of Tarsus universalizes the Jewish message for gentiles. In China, the Han dynasty's iron furnaces and paper drafts push it ahead of Rome in some technologies, behind in others. The Buddha's teachings reach the Han court.",
      zh: "一位加利利木匠被罗马总督钉上十字架；他的追随者，违反一切合理预测，将在三个世纪内接管罗马帝国。罗马和平为他们铺平道路。塔尔苏斯的保罗把犹太教信息普世化，向外邦人开放。中国，汉朝的铁炉与纸张草稿在某些技术上超越罗马，另一些技术上落后。佛陀的教义传入汉朝宫廷。",
    },
    events: [
      { y: "≈ 4 BCE", en: "Birth of Jesus of Nazareth (most likely).", zh: "拿撒勒的耶稣诞生（可能年份）。" },
      { y: "≈ 30", en: "Crucifixion of Jesus.", zh: "耶稣被钉十字架。" },
      { y: "64", en: "Great Fire of Rome; Nero blames Christians.", zh: "罗马大火；尼禄归咎于基督徒。" },
      { y: "70", en: "Romans destroy the Second Temple in Jerusalem.", zh: "罗马摧毁耶路撒冷第二圣殿。" },
      { y: "79", en: "Vesuvius destroys Pompeii and Herculaneum.", zh: "维苏威火山摧毁庞贝与赫库兰尼姆。" },
      { y: "105", en: "Paper invented (or refined) in Han China by Cai Lun.", zh: "蔡伦改进造纸术。" },
    ],
    figures: [
      { en: "Jesus of Nazareth", zh: "拿撒勒的耶稣" },
      { en: "Paul of Tarsus", zh: "塔尔苏斯的保罗" },
      { en: "Augustus / Tiberius / Nero", zh: "奥古斯都 / 提比略 / 尼禄" },
      { en: "Cai Lun", zh: "蔡伦" },
    ],
    invented: { en: "Universalist religion. Paper. The Pax Romana as a brand.", zh: "普世性宗教。纸张。作为品牌的罗马和平。" },
    ended: { en: "Religious life as a strictly ethnic affair.", zh: "宗教生活作为严格民族事务的形态。" },
    legacy: { en: "Half the world is still organized around what happened in this one province.", zh: "今天世界半数人口的组织方式，仍取决于发生在那一个省份的事。" },
    color: "#d4a85a",
  },
  {
    id: "ce-2",
    label: { en: "2nd century", zh: "公元 2 世纪" },
    romanCentury: "II",
    yearRange: "101–200 CE",
    era: "pax-romana",
    theme: { en: "Pax Romana", zh: "罗马和平" },
    themeShort: { en: "Five Good Emperors · Han apex · global plague", zh: "五贤帝 · 汉朝顶峰 · 全球瘟疫" },
    region: { en: "Rome · China · India", zh: "罗马 · 中国 · 印度" },
    body: {
      en: "The Roman Empire reaches its largest extent under Trajan; Hadrian builds a wall in northern Britain. Marcus Aurelius writes the Meditations on campaign. The Han dynasty produces seismographs, the magnetic compass, and the world's largest library. The two empires — neither aware of the other except by rumor — together hold a quarter of humanity. Then, at century's end, the Antonine Plague kills perhaps ten million.",
      zh: "罗马帝国在图拉真治下达到版图最大；哈德良在不列颠北部修筑长城。马可·奥勒留在征途中写下《沉思录》。汉朝制造出地动仪、磁石指南针，以及当时世界上最大的图书馆。两个帝国 —— 互不了解，仅闻其名 —— 合计承载着四分之一的人类。然后，世纪之末，安东尼瘟疫夺走或许一千万人。",
    },
    events: [
      { y: "117", en: "Roman Empire reaches greatest extent under Trajan.", zh: "罗马帝国在图拉真治下版图最大。" },
      { y: "122", en: "Hadrian's Wall begun.", zh: "哈德良长城动工。" },
      { y: "132", en: "Zhang Heng demonstrates the first seismograph (China).", zh: "张衡演示首台地动仪（中国）。" },
      { y: "≈ 175", en: "Marcus Aurelius writes the Meditations.", zh: "马可·奥勒留写《沉思录》。" },
      { y: "165", en: "Antonine Plague sweeps the empire.", zh: "安东尼瘟疫席卷帝国。" },
    ],
    figures: [
      { en: "Trajan", zh: "图拉真" },
      { en: "Hadrian", zh: "哈德良" },
      { en: "Marcus Aurelius", zh: "马可·奥勒留" },
      { en: "Zhang Heng", zh: "张衡" },
    ],
    invented: { en: "Stoic philosophy as imperial practice. Seismography. The transnational pandemic.", zh: "作为帝国实践的斯多葛哲学。地震学。跨国大流行病。" },
    ended: { en: "The illusion that empire was permanent.", zh: "帝国是永恒的这一幻觉。" },
    legacy: { en: "One of the longest peaces in recorded history, and the philosophy book most read in offices today.", zh: "有记载历史上最长的和平之一，也是今天写字楼里最被传阅的一本哲学书。" },
    color: "#d4a85a",
  },
  {
    id: "ce-3",
    label: { en: "3rd century", zh: "公元 3 世纪" },
    romanCentury: "III",
    yearRange: "201–300 CE",
    era: "late-antiquity",
    theme: { en: "Crisis of the Third Century", zh: "帝国危机" },
    themeShort: { en: "Fifty emperors · plague · inflation", zh: "五十位皇帝 · 瘟疫 · 通胀" },
    region: { en: "Rome · Persia · China", zh: "罗马 · 波斯 · 中国" },
    body: {
      en: "In fifty years Rome has more than fifty emperors, most assassinated. The currency debases; the borders leak; the Sasanian Persians capture a Roman emperor alive. In China the Han collapses into the Three Kingdoms — the period later mythologized in the Romance of the Three Kingdoms. Diocletian arrives at century's end to reorganize Rome, dividing it east and west. The crisis is survived; the unity is not.",
      zh: "五十年里，罗马有过五十多位皇帝，多数死于刺杀。货币贬值；边境失守；萨珊波斯活捉一位罗马皇帝。中国，汉朝崩为三国 —— 日后被《三国演义》神话化的时代。世纪末，戴克里先到来重组罗马，将其一分为东西。危机被熬过；统一未能保住。",
    },
    events: [
      { y: "212", en: "Caracalla grants Roman citizenship to all free men.", zh: "卡拉卡拉敕令将公民权扩展至全帝国自由人。" },
      { y: "220", en: "Han dynasty ends; Three Kingdoms period in China.", zh: "汉朝终结；中国进入三国时代。" },
      { y: "260", en: "Roman Emperor Valerian captured by Persia.", zh: "罗马皇帝瓦勒良被波斯俘获。" },
      { y: "284", en: "Diocletian reorganizes the empire into a tetrarchy.", zh: "戴克里先将帝国改组为四帝共治。" },
    ],
    figures: [
      { en: "Diocletian", zh: "戴克里先" },
      { en: "Shapur I (Persia)", zh: "沙普尔一世（波斯）" },
      { en: "Cao Cao", zh: "曹操" },
      { en: "Liu Bei", zh: "刘备" },
    ],
    invented: { en: "Late-Roman fiscal reform. The administrative split that will become Byzantium.", zh: "罗马晚期财政改革。日后形成拜占庭的行政分治。" },
    ended: { en: "The classical Roman Empire as a single coherent entity.", zh: "作为统一实体的古典罗马帝国。" },
    legacy: { en: "Proof that complex civilizations can run on autopilot through fifty years of chaos and still survive.", zh: "证明复杂文明能在五十年混乱中以惯性运行并存活下来。" },
    color: "#a18b6f",
  },
  {
    id: "ce-4",
    label: { en: "4th century", zh: "公元 4 世纪" },
    romanCentury: "IV",
    yearRange: "301–400 CE",
    era: "late-antiquity",
    theme: { en: "Christianity Legalized", zh: "基督教合法化" },
    themeShort: { en: "Constantine · Council of Nicaea · Constantinople", zh: "君士坦丁 · 尼西亚会议 · 君士坦丁堡" },
    region: { en: "Rome · Constantinople · India", zh: "罗马 · 君士坦丁堡 · 印度" },
    body: {
      en: "Constantine wins at the Milvian Bridge under a Christian sign and, with the Edict of Milan, legalizes a once-persecuted sect. He founds Constantinople — a new Rome that will outlast the old one by a thousand years. The Council of Nicaea hammers Christianity into a creed. In India, the Gupta dynasty inaugurates a classical age of mathematics (zero, decimal place value) and science. The medieval shape of the world is forming.",
      zh: "君士坦丁在十字标记下赢得米尔维安桥战役，颁布《米兰敕令》，将曾被迫害的教派合法化。他建造君士坦丁堡 —— 一座『新罗马』，将比旧罗马多活一千年。尼西亚会议将基督教锻造为信经。印度，笈多王朝开启数学（零、十进制位值）与科学的古典时代。中世纪世界的轮廓正在成形。",
    },
    events: [
      { y: "313", en: "Edict of Milan: Christianity legalized.", zh: "《米兰敕令》：基督教合法化。" },
      { y: "325", en: "Council of Nicaea fixes Christian doctrine.", zh: "尼西亚公会议确立基督教教义。" },
      { y: "330", en: "Constantinople founded as the new Rome.", zh: "君士坦丁堡作为『新罗马』建立。" },
      { y: "320", en: "Gupta Empire founded in India.", zh: "笈多王朝在印度建立。" },
      { y: "380", en: "Christianity becomes the Roman state religion.", zh: "基督教成为罗马国教。" },
    ],
    figures: [
      { en: "Constantine the Great", zh: "君士坦丁大帝" },
      { en: "Theodosius I", zh: "狄奥多西一世" },
      { en: "Augustine of Hippo", zh: "希波的奥古斯丁" },
      { en: "Chandragupta II", zh: "旃陀罗笈多二世" },
    ],
    invented: { en: "The Christian Roman world. Mathematical zero as a positional digit.", zh: "基督教罗马世界。作为位值数字的零。" },
    ended: { en: "Pagan Rome.", zh: "异教罗马。" },
    legacy: { en: "A religion becomes an empire. An empire becomes a religion.", zh: "宗教变成帝国。帝国变成宗教。" },
    color: "#a18b6f",
  },
  {
    id: "ce-5",
    label: { en: "5th century", zh: "公元 5 世纪" },
    romanCentury: "V",
    yearRange: "401–500 CE",
    era: "late-antiquity",
    theme: { en: "Fall of Western Rome", zh: "西罗马帝国覆灭" },
    themeShort: { en: "Goths · Vandals · Attila · 476", zh: "哥特 · 汪达尔 · 阿提拉 · 476" },
    region: { en: "Western Europe · North Africa · China", zh: "西欧 · 北非 · 中国" },
    body: {
      en: "Goths sack Rome (410). Vandals sack Rome (455). Attila threatens both halves of the empire. In 476 the last Western Roman emperor is deposed; no one at the time treats it as the end of an era — it was a slow fade, not a thunderclap. Augustine writes the City of God to explain why a Christian Rome could fall. In China, the period of disunity continues. Buddhism spreads. The world without Rome begins.",
      zh: "哥特人攻陷罗马（410）。汪达尔人再洗劫罗马（455）。阿提拉同时威胁帝国东西两半。476 年，最后一位西罗马皇帝被废；当时无人将其视为时代的终结 —— 那是缓慢的褪色，而非一声惊雷。奥古斯丁写《上帝之城》，解释为何一个基督教罗马会陷落。中国，分裂仍在继续。佛教传播。没有罗马的世界，由此开启。",
    },
    events: [
      { y: "410", en: "Visigoths under Alaric sack Rome.", zh: "西哥特人在阿拉里克率领下攻陷罗马。" },
      { y: "426", en: "Augustine finishes the City of God.", zh: "奥古斯丁完成《上帝之城》。" },
      { y: "451", en: "Attila defeated at Châlons.", zh: "阿提拉在沙隆战败。" },
      { y: "455", en: "Vandals sack Rome.", zh: "汪达尔人再洗劫罗马。" },
      { y: "476", en: "Last Western Roman Emperor deposed.", zh: "末任西罗马皇帝被废。" },
    ],
    figures: [
      { en: "Augustine of Hippo", zh: "希波的奥古斯丁" },
      { en: "Attila the Hun", zh: "匈人王阿提拉" },
      { en: "Alaric", zh: "阿拉里克" },
      { en: "Odoacer", zh: "奥多亚塞" },
    ],
    invented: { en: "Christian theology of history. The medieval idea of Europe.", zh: "基督教历史神学。中世纪欧洲的观念。" },
    ended: { en: "The Western Roman Empire as a continuous political entity.", zh: "作为延续政治实体的西罗马帝国。" },
    legacy: { en: "The reference event for every later collapse anxiety.", zh: "此后所有『崩溃焦虑』的参照事件。" },
    color: "#a18b6f",
  },
  {
    id: "ce-6",
    label: { en: "6th century", zh: "公元 6 世纪" },
    romanCentury: "VI",
    yearRange: "501–600 CE",
    era: "early-medieval",
    theme: { en: "Byzantine Revival", zh: "拜占庭复兴" },
    themeShort: { en: "Justinian · Hagia Sophia · the Code", zh: "查士丁尼 · 圣索菲亚 · 法典" },
    region: { en: "Constantinople · Italy · China", zh: "君士坦丁堡 · 意大利 · 中国" },
    body: {
      en: "Justinian briefly reconquers Italy and North Africa, codifies Roman law into the Corpus Juris Civilis, and builds Hagia Sophia — for nearly a thousand years the largest cathedral in the world. Then the Plague of Justinian arrives, killing perhaps a quarter of the Mediterranean basin. In China, the Sui dynasty briefly reunifies the country and digs the Grand Canal, the longest artificial waterway in history.",
      zh: "查士丁尼短暂收复意大利与北非，将罗马法编纂为《查士丁尼法典》，并建造圣索菲亚大教堂 —— 在近千年里它将是世界最大的教堂。然后查士丁尼瘟疫到来，杀死或许四分之一的地中海人口。中国，隋朝短暂重新统一，开凿大运河 —— 历史上最长的人工水道。",
    },
    events: [
      { y: "527", en: "Justinian becomes Byzantine emperor.", zh: "查士丁尼即位为拜占庭皇帝。" },
      { y: "529", en: "Plato's Academy closed in Athens.", zh: "雅典柏拉图学园被关闭。" },
      { y: "537", en: "Hagia Sophia completed.", zh: "圣索菲亚大教堂建成。" },
      { y: "541", en: "Plague of Justinian begins.", zh: "查士丁尼瘟疫开始。" },
      { y: "581", en: "Sui dynasty reunifies China.", zh: "隋朝重新统一中国。" },
    ],
    figures: [
      { en: "Justinian I", zh: "查士丁尼一世" },
      { en: "Theodora", zh: "狄奥多拉" },
      { en: "Belisarius", zh: "贝利撒留" },
      { en: "Emperor Wen of Sui", zh: "隋文帝" },
    ],
    invented: { en: "Codified civil law. Pendentive dome architecture. The Grand Canal.", zh: "成文民法。穹隅穹顶建筑。京杭大运河。" },
    ended: { en: "Athens as a center of pagan philosophy.", zh: "雅典作为异教哲学中心的地位。" },
    legacy: { en: "Roman law passes through Justinian into every continental legal system today.", zh: "罗马法经查士丁尼之手，进入今天每一个大陆法系。" },
    color: "#a18b6f",
  },
  {
    id: "ce-7",
    label: { en: "7th century", zh: "公元 7 世纪" },
    romanCentury: "VII",
    yearRange: "601–700 CE",
    era: "early-medieval",
    theme: { en: "The Rise of Islam", zh: "伊斯兰兴起" },
    themeShort: { en: "Muhammad · the Hijra · the Caliphate · Tang", zh: "穆罕默德 · 希吉拉 · 哈里发 · 大唐" },
    region: { en: "Arabia · Iran · North Africa · Tang China", zh: "阿拉伯 · 伊朗 · 北非 · 大唐" },
    body: {
      en: "In one century, an Arabian merchant becomes a prophet, then a political leader, then dies — and his followers, in less than a hundred years, conquer Persia, Egypt, and march to Tours. The Sasanian Empire vanishes. Byzantium loses most of its territory. Half the Christian world becomes Muslim. Meanwhile in China, the Tang dynasty inaugurates East Asia's most cosmopolitan era — Persian poets at Chang'an, monks copying Indian sutras.",
      zh: "一个世纪内：一位阿拉伯商人成为先知，再成为政治领袖，然后辞世 —— 而他的追随者，在不到百年内征服波斯、埃及，挺进图尔。萨珊帝国消失。拜占庭丧失大部分领土。基督教世界的一半皈依伊斯兰。同时，中国大唐开启东亚最具世界主义气质的时代 —— 波斯诗人在长安作诗，僧人抄印度经卷。",
    },
    events: [
      { y: "618", en: "Tang dynasty founded.", zh: "唐朝建立。" },
      { y: "622", en: "The Hijra: Muhammad and followers move from Mecca to Medina.", zh: "希吉拉：穆罕默德及其追随者由麦加迁往麦地那。" },
      { y: "632", en: "Death of Muhammad. Rashidun Caliphate begins.", zh: "穆罕默德归真。正统哈里发时代开始。" },
      { y: "651", en: "Sasanian Persian Empire collapses.", zh: "萨珊波斯帝国崩溃。" },
      { y: "661", en: "Umayyad Caliphate established.", zh: "伍麦叶哈里发国建立。" },
    ],
    figures: [
      { en: "Muhammad", zh: "穆罕默德" },
      { en: "Umar I", zh: "欧麦尔一世" },
      { en: "Empress Wu Zetian", zh: "武则天" },
      { en: "Emperor Taizong of Tang", zh: "唐太宗" },
    ],
    invented: { en: "Islam as a civilization. A unified Arabic-script intellectual world.", zh: "作为文明的伊斯兰。统一的阿拉伯文知识世界。" },
    ended: { en: "Sasanian Persia. Byzantine dominance of the Levant.", zh: "萨珊波斯。拜占庭对黎凡特的支配。" },
    legacy: { en: "Half the world's geopolitical map still inherits decisions made this century.", zh: "今天世界一半的地缘版图，仍承袭本世纪的决定。" },
    color: "#a18b6f",
  },
  {
    id: "ce-8",
    label: { en: "8th century", zh: "公元 8 世纪" },
    romanCentury: "VIII",
    yearRange: "701–800 CE",
    era: "early-medieval",
    theme: { en: "The Carolingian Empire", zh: "查理曼帝国" },
    themeShort: { en: "Charlemagne · An Lushan · Abbasids · Baghdad", zh: "查理曼 · 安史之乱 · 阿拔斯 · 巴格达" },
    region: { en: "Frankish Europe · Tang China · Baghdad", zh: "法兰克欧洲 · 大唐 · 巴格达" },
    body: {
      en: "Charlemagne is crowned by the Pope on Christmas Day 800 — the symbolic restart of a Western emperor. The Abbasids found Baghdad, which by century's end is the largest city in the world. Greek, Persian, and Indian knowledge is translated there into Arabic; algebra is born; the zero, borrowed from India, enters the world's accounting. In China, the An Lushan rebellion devastates the Tang and ends an era of cosmopolitan glory.",
      zh: "公元 800 年圣诞节，查理曼被教皇加冕 —— 西方皇帝的象征性重启。阿拔斯王朝建立巴格达，世纪之末它是世界最大城市。希腊、波斯、印度的知识在此被译为阿拉伯文；代数诞生；从印度借来的零，进入世界的账本。中国，安史之乱重创大唐，结束了一个世界主义辉煌的时代。",
    },
    events: [
      { y: "711", en: "Muslim conquest of Iberia begins.", zh: "穆斯林征服伊比利亚开始。" },
      { y: "732", en: "Charles Martel halts Muslim advance at Tours.", zh: "查理·马特在图尔阻止穆斯林北进。" },
      { y: "755", en: "An Lushan Rebellion devastates Tang China.", zh: "安史之乱重创大唐。" },
      { y: "762", en: "Baghdad founded by Caliph al-Mansur.", zh: "哈里发曼苏尔建立巴格达。" },
      { y: "800", en: "Charlemagne crowned Holy Roman Emperor.", zh: "查理曼加冕为神圣罗马皇帝。" },
    ],
    figures: [
      { en: "Charlemagne", zh: "查理曼" },
      { en: "Harun al-Rashid", zh: "哈伦·拉希德" },
      { en: "al-Khwarizmi", zh: "花拉子米" },
      { en: "An Lushan", zh: "安禄山" },
    ],
    invented: { en: "Algebra. The Holy Roman emperor. Carolingian minuscule (modern lower-case).", zh: "代数。神圣罗马皇帝。加洛林小写体（现代小写字母）。" },
    ended: { en: "The all-Greek Mediterranean intellectual world.", zh: "全希腊语的地中海知识世界。" },
    legacy: { en: "Baghdad and Aachen become twin engines that will preserve and transmit Greek thought back to Europe.", zh: "巴格达与亚琛成为一对引擎，把希腊思想保存并传回欧洲。" },
    color: "#a18b6f",
  },
  {
    id: "ce-9",
    label: { en: "9th century", zh: "公元 9 世纪" },
    romanCentury: "IX",
    yearRange: "801–900 CE",
    era: "early-medieval",
    theme: { en: "Viking Expansion", zh: "维京扩张" },
    themeShort: { en: "Longships · Kievan Rus · House of Wisdom", zh: "长船 · 基辅罗斯 · 智慧宫" },
    region: { en: "Scandinavia · Slavic lands · Baghdad", zh: "斯堪的纳维亚 · 斯拉夫诸地 · 巴格达" },
    body: {
      en: "Vikings raid, then trade, then settle — from Ireland to the Volga to Constantinople. They found the state that becomes Russia. In Baghdad, the House of Wisdom translates Aristotle, Galen, and Indian astronomy into Arabic. Cyril and Methodius design the Glagolitic script for the Slavs. In China, the Tang fades; gunpowder is mentioned in alchemical texts for the first time.",
      zh: "维京人先劫掠、后贸易、再定居 —— 从爱尔兰到伏尔加再到君士坦丁堡。他们建立了日后将成为俄罗斯的国家。巴格达，智慧宫把亚里士多德、盖伦与印度天文译为阿拉伯文。西里尔与美多德为斯拉夫人设计格拉哥里字母。中国，大唐衰落；火药首次出现在炼丹文献中。",
    },
    events: [
      { y: "793", en: "Lindisfarne raid: Viking Age begins.", zh: "林迪斯法恩劫掠：维京时代开始。" },
      { y: "813", en: "Caliph al-Ma'mun expands the House of Wisdom.", zh: "哈里发马蒙扩建智慧宫。" },
      { y: "843", en: "Treaty of Verdun divides Carolingian Empire.", zh: "凡尔登条约分裂加洛林帝国。" },
      { y: "862", en: "Rurik founds Novgorod; Kievan Rus origins.", zh: "留里克建立诺夫哥罗德；基辅罗斯起源。" },
      { y: "≈ 850", en: "First mention of gunpowder in Chinese texts.", zh: "中国文献首次提及火药。" },
    ],
    figures: [
      { en: "Alfred the Great", zh: "阿尔弗雷德大帝" },
      { en: "Rurik", zh: "留里克" },
      { en: "al-Khwarizmi", zh: "花拉子米" },
      { en: "Cyril and Methodius", zh: "西里尔与美多德" },
    ],
    invented: { en: "Long-distance Atlantic raiding. Algorithmic mathematics. Slavic literacy.", zh: "远洋大西洋劫掠。算法数学。斯拉夫识字。" },
    ended: { en: "Carolingian Europe as a single political block.", zh: "作为统一政治块的加洛林欧洲。" },
    legacy: { en: "Russia, England, France, and Iceland all trace political ancestry to this century.", zh: "俄罗斯、英格兰、法兰西、冰岛 —— 都将政治祖先追溯到这个世纪。" },
    color: "#a18b6f",
  },
  {
    id: "ce-10",
    label: { en: "10th century", zh: "公元 10 世纪" },
    romanCentury: "X",
    yearRange: "901–1000 CE",
    era: "early-medieval",
    theme: { en: "The Holy Roman Empire", zh: "神圣罗马帝国" },
    themeShort: { en: "Ottonian revival · Song China · Cairo", zh: "奥托复兴 · 大宋 · 开罗" },
    region: { en: "Germany · Italy · Song China · Egypt", zh: "德意志 · 意大利 · 大宋 · 埃及" },
    body: {
      en: "Otto I revives the Western imperial title — the Holy Roman Empire that will lurch on for 800 years. In China, the Song dynasty inaugurates a commercial and technological golden age: printed books, paper money, the magnetic compass, and government civil-service exams that select bureaucrats by literacy not lineage. The Fatimids found Cairo. Iceland adopts Christianity by vote in 1000. The High Middle Ages are beginning.",
      zh: "奥托一世复活了西方帝号 —— 此后摇晃八百年的神圣罗马帝国。中国，宋朝开启商业与技术的黄金时代：印刷书籍、纸币、指南针，以及以识字而非门第选官的科举制。法蒂玛王朝兴建开罗。冰岛于公元 1000 年以投票方式皈依基督教。中世纪盛期正在开启。",
    },
    events: [
      { y: "960", en: "Song dynasty founded in China.", zh: "宋朝建立。" },
      { y: "962", en: "Otto I crowned Holy Roman Emperor.", zh: "奥托一世加冕为神圣罗马皇帝。" },
      { y: "969", en: "Cairo founded by the Fatimids.", zh: "法蒂玛王朝建立开罗。" },
      { y: "988", en: "Vladimir of Kiev converts Rus to Eastern Christianity.", zh: "基辅大公弗拉基米尔皈依东正教。" },
      { y: "1000", en: "Iceland converts to Christianity by parliamentary vote.", zh: "冰岛以议会投票皈依基督教。" },
    ],
    figures: [
      { en: "Otto I", zh: "奥托一世" },
      { en: "Emperor Taizu of Song", zh: "宋太祖（赵匡胤）" },
      { en: "Vladimir the Great", zh: "弗拉基米尔大公" },
      { en: "al-Mu'izz (Fatimid)", zh: "穆伊兹（法蒂玛）" },
    ],
    invented: { en: "Printing (movable woodblock). Paper money. Civil-service exams. Holy Roman Empire.", zh: "雕版印刷。纸币。科举制。神圣罗马帝国。" },
    ended: { en: "Carolingian fragmentation. Aristocratic monopoly on administration in China.", zh: "加洛林碎片化。中国行政被贵族垄断的格局。" },
    legacy: { en: "China runs ahead of Europe by half a millennium; Europe begins to coalesce again.", zh: "中国领先欧洲半个千年；欧洲开始重新凝聚。" },
    color: "#a18b6f",
  },
  {
    id: "ce-11",
    label: { en: "11th century", zh: "公元 11 世纪" },
    romanCentury: "XI",
    yearRange: "1001–1100 CE",
    era: "high-medieval",
    theme: { en: "The Norman Conquest", zh: "诺曼征服" },
    themeShort: { en: "Hastings · Schism · Investiture · Avicenna", zh: "黑斯廷斯 · 大分裂 · 主教叙任之争 · 伊本·西那" },
    region: { en: "England · Rome · Persia · Song China", zh: "英格兰 · 罗马 · 波斯 · 大宋" },
    body: {
      en: "In 1054 the Catholic West and Orthodox East formally split — a schism that has not yet healed. In 1066 William of Normandy invades England; for two and a half centuries the Anglo-Saxon language vanishes from court and law. Avicenna in Persia writes the Canon of Medicine — Europe's medical textbook until the 17th century. In China, Bi Sheng invents movable-type printing, four centuries before Gutenberg. The Crusades approach.",
      zh: "1054 年，天主教西方与东正教东方正式分裂 —— 至今未愈的大分裂。1066 年，诺曼底的威廉入侵英格兰；此后两个半世纪里，盎格鲁-撒克逊语从宫廷与法律中消失。波斯，伊本·西那写下《医典》—— 欧洲直到 17 世纪的医学教科书。中国，毕昇发明活字印刷，比古腾堡早四个世纪。十字军即将来临。",
    },
    events: [
      { y: "1054", en: "Great Schism between Catholic and Orthodox churches.", zh: "东西教会大分裂。" },
      { y: "1066", en: "Norman Conquest of England.", zh: "诺曼征服英格兰。" },
      { y: "1071", en: "Battle of Manzikert: Byzantines lose Anatolia.", zh: "曼齐刻尔特战役：拜占庭丧失安纳托利亚。" },
      { y: "1077", en: "Henry IV humiliated at Canossa by Pope Gregory VII.", zh: "亨利四世在卡诺萨向教皇格里高利七世屈膝。" },
      { y: "1095", en: "Pope Urban II calls the First Crusade.", zh: "教皇乌尔班二世发起第一次十字军。" },
      { y: "≈ 1040", en: "Bi Sheng invents movable-type printing in China.", zh: "毕昇发明活字印刷。" },
    ],
    figures: [
      { en: "William the Conqueror", zh: "征服者威廉" },
      { en: "Pope Gregory VII", zh: "教皇格里高利七世" },
      { en: "Avicenna (Ibn Sina)", zh: "伊本·西那" },
      { en: "Bi Sheng", zh: "毕昇" },
    ],
    invented: { en: "Movable-type print (China). The Catholic / Orthodox split. The university (Bologna, 1088).", zh: "活字印刷（中国）。天主教 / 东正教分裂。大学（博洛尼亚，1088）。" },
    ended: { en: "Anglo-Saxon England. Byzantine grip on Anatolia.", zh: "盎格鲁-撒克逊英格兰。拜占庭对安纳托利亚的控制。" },
    legacy: { en: "The English language merges Old English with Norman French — the language you are reading.", zh: "英语将古英语与诺曼法语融合 —— 也就是你正在读的语言。" },
    color: "#c9a96e",
  },
  {
    id: "ce-12",
    label: { en: "12th century", zh: "公元 12 世纪" },
    romanCentury: "XII",
    yearRange: "1101–1200 CE",
    era: "high-medieval",
    theme: { en: "The Crusades", zh: "十字军东征" },
    themeShort: { en: "Cathedrals · universities · Aquinas's grandfathers", zh: "大教堂 · 大学 · 学院哲学的祖父辈" },
    region: { en: "Levant · Europe · Song China · Japan", zh: "黎凡特 · 欧洲 · 大宋 · 日本" },
    body: {
      en: "The Crusades wash over the Levant for two centuries. Aristotle returns to the Latin West via Arabic translations through Toledo. Gothic cathedrals begin to rise. Paris and Bologna become true universities. Eleanor of Aquitaine rules half of France and most of England. Heloise and Abelard write their love letters. In Japan, the samurai class consolidates. In China, neo-Confucianism takes shape under Zhu Xi.",
      zh: "十字军连续两个世纪冲洗黎凡特。亚里士多德经由托莱多的阿拉伯文译本回到拉丁西方。哥特式大教堂开始升起。巴黎与博洛尼亚成为真正的大学。阿基坦的埃莉诺统治法国半壁与英格兰大部。赫洛伊兹与阿伯拉尔写下情书。日本，武士阶级凝固。中国，理学在朱熹手中成形。",
    },
    events: [
      { y: "1099", en: "First Crusade captures Jerusalem.", zh: "第一次十字军攻占耶路撒冷。" },
      { y: "1135", en: "Eleanor of Aquitaine born; rules half of France.", zh: "阿基坦的埃莉诺出生；统治法国半壁。" },
      { y: "1163", en: "Construction of Notre-Dame de Paris begins.", zh: "巴黎圣母院动工。" },
      { y: "1187", en: "Saladin retakes Jerusalem.", zh: "萨拉丁收复耶路撒冷。" },
      { y: "1185", en: "Kamakura shogunate established in Japan.", zh: "日本镰仓幕府建立。" },
    ],
    figures: [
      { en: "Saladin", zh: "萨拉丁" },
      { en: "Eleanor of Aquitaine", zh: "阿基坦的埃莉诺" },
      { en: "Pierre Abélard", zh: "皮埃尔·阿伯拉尔" },
      { en: "Zhu Xi", zh: "朱熹" },
    ],
    invented: { en: "The Gothic cathedral. The chartered medieval university. Neo-Confucianism.", zh: "哥特式大教堂。特许的中世纪大学。理学。" },
    ended: { en: "The European amnesia of Aristotle.", zh: "欧洲对亚里士多德的遗忘。" },
    legacy: { en: "Universities, cathedrals, and the East-meets-West encounter that will compound for 800 years.", zh: "大学、大教堂，以及此后将持续 800 年累计的东西方相遇。" },
    color: "#c9a96e",
  },
  {
    id: "ce-13",
    label: { en: "13th century", zh: "公元 13 世纪" },
    romanCentury: "XIII",
    yearRange: "1201–1300 CE",
    era: "high-medieval",
    theme: { en: "The Mongol Empire", zh: "蒙古帝国" },
    themeShort: { en: "Largest contiguous empire in history", zh: "史上最大相连帝国" },
    region: { en: "Mongolia · Eurasia · England", zh: "蒙古 · 欧亚 · 英格兰" },
    body: {
      en: "Genghis Khan and his successors conquer from the Pacific to the Black Sea. Pax Mongolica makes overland Eurasia safe enough for Marco Polo to travel home with stories. Magna Carta is signed (1215). Aquinas synthesizes Aristotle and Christianity. Hangzhou under the Song is, on Marco Polo's report, the largest and most prosperous city on Earth. Then the Mongol storm hits the Song.",
      zh: "成吉思汗及其后继者从太平洋征服至黑海。蒙古和平让陆上欧亚足够安全，马可·波罗得以满载故事归乡。《大宪章》签订（1215）。阿奎那综合亚里士多德与基督教。大宋治下的杭州，依马可·波罗记载，是当时世界上最大、最繁荣的城市。然后蒙古风暴撞上南宋。",
    },
    events: [
      { y: "1206", en: "Genghis Khan unites the Mongol tribes.", zh: "成吉思汗统一蒙古诸部。" },
      { y: "1215", en: "Magna Carta signed in England.", zh: "英格兰签订《大宪章》。" },
      { y: "1258", en: "Mongols sack Baghdad; end of the Abbasid Caliphate.", zh: "蒙古攻陷巴格达；阿拔斯哈里发国终结。" },
      { y: "1271", en: "Marco Polo begins his journey to China.", zh: "马可·波罗启程东行。" },
      { y: "1279", en: "Mongols conquer the Song; Yuan dynasty established.", zh: "蒙古灭宋；元朝建立。" },
    ],
    figures: [
      { en: "Genghis Khan", zh: "成吉思汗" },
      { en: "Kublai Khan", zh: "忽必烈" },
      { en: "Thomas Aquinas", zh: "托马斯·阿奎那" },
      { en: "Marco Polo", zh: "马可·波罗" },
    ],
    invented: { en: "Continental free trade by force. Scholastic synthesis. Constitutional limit on monarchy.", zh: "以武力达成的大陆自由贸易。学院综合。对君权的宪法限制。" },
    ended: { en: "Abbasid Caliphate. Song-dynasty independence.", zh: "阿拔斯哈里发国。南宋独立。" },
    legacy: { en: "Eurasia experiences its first single market and pandemic-ready connectivity.", zh: "欧亚第一次拥有单一市场，以及随之而来的疫病传播路径。" },
    color: "#c9a96e",
  },
  {
    id: "ce-14",
    label: { en: "14th century", zh: "公元 14 世纪" },
    romanCentury: "XIV",
    yearRange: "1301–1400 CE",
    era: "crisis-renaissance",
    theme: { en: "The Black Death", zh: "黑死病" },
    themeShort: { en: "Plague · the Hundred Years' War · Mali · Dante", zh: "瘟疫 · 百年战争 · 马里 · 但丁" },
    region: { en: "Europe · Mali · Yuan / Ming China", zh: "欧洲 · 马里 · 元 / 明中国" },
    body: {
      en: "The plague kills perhaps a third of Europe in five years. Wages rise; serfdom cracks; the Renaissance gets its labor market. The Hundred Years' War begins. Dante completes the Divine Comedy. In Mali, Mansa Musa is, by some calculations, the richest person who has ever lived. In China, the Ming overthrow the Mongols and turn inward. The medieval world will not recover its old shape.",
      zh: "黑死病五年内杀死或许三分之一的欧洲人。工资上涨；农奴制松动；文艺复兴获得了它的劳动力市场。百年战争爆发。但丁完成《神曲》。马里，曼萨·穆萨按某些计算是有史以来最富有的人。中国，明朝推翻蒙古并转向内陆。中世纪世界，再也不会恢复旧有的形态。",
    },
    events: [
      { y: "1314", en: "Dante completes Inferno; later the full Divine Comedy.", zh: "但丁完成《地狱篇》；后续完成《神曲》全本。" },
      { y: "1324", en: "Mansa Musa's pilgrimage to Mecca destabilizes Mediterranean gold.", zh: "曼萨·穆萨朝觐麦加，扰动地中海金价。" },
      { y: "1337", en: "Hundred Years' War begins.", zh: "英法百年战争爆发。" },
      { y: "1347", en: "Black Death reaches Europe.", zh: "黑死病登陆欧洲。" },
      { y: "1368", en: "Ming dynasty founded; Mongols expelled from China.", zh: "明朝建立；蒙古被逐出中国。" },
    ],
    figures: [
      { en: "Dante Alighieri", zh: "但丁" },
      { en: "Mansa Musa", zh: "曼萨·穆萨" },
      { en: "Geoffrey Chaucer", zh: "乔叟" },
      { en: "Zhu Yuanzhang (Hongwu)", zh: "朱元璋（洪武帝）" },
    ],
    invented: { en: "Post-plague labor economics. Vernacular literature as high art. The cannon.", zh: "瘟疫后的劳动力经济。作为高雅艺术的本土语文学。火炮。" },
    ended: { en: "Manorial serfdom in Western Europe. Mongol rule in China.", zh: "西欧庄园农奴制。蒙古对中国的统治。" },
    legacy: { en: "Demographic collapse that triggers the early modern world.", zh: "人口崩溃，触发近代早期世界。" },
    color: "#a83232",
  },
  {
    id: "ce-15",
    label: { en: "15th century", zh: "公元 15 世纪" },
    romanCentury: "XV",
    yearRange: "1401–1500 CE",
    era: "crisis-renaissance",
    theme: { en: "The Renaissance", zh: "文艺复兴" },
    themeShort: { en: "Gutenberg · Columbus · 1492 · Zheng He", zh: "古腾堡 · 哥伦布 · 1492 · 郑和" },
    region: { en: "Italy · Iberia · Ming China · Americas", zh: "意大利 · 伊比利亚 · 大明 · 美洲" },
    body: {
      en: "Gutenberg prints with movable metal type around 1450 — the European information explosion begins. Constantinople falls (1453); Greek scholars flee to Italy. Florence funds Brunelleschi's dome and Botticelli's paintings. Zheng He sails the Ming treasure fleet to East Africa, then Ming China abruptly retreats from the sea. Columbus reaches the Caribbean (1492). The same year, the Reconquista ends and the Jews are expelled from Spain. The early modern world is born.",
      zh: "1450 年前后，古腾堡以金属活字印刷 —— 欧洲信息爆炸开始。君士坦丁堡陷落（1453）；希腊学者逃往意大利。佛罗伦萨资助布鲁内莱斯基的穹顶与波提切利的画。郑和率明朝宝船舰队远抵东非，随后大明骤然退出海洋。哥伦布抵达加勒比（1492）。同年，再征服战争结束，犹太人被逐出西班牙。近代早期世界，由此诞生。",
    },
    events: [
      { y: "1405", en: "Zheng He launches the first Ming treasure voyage.", zh: "郑和首次下西洋。" },
      { y: "1450", en: "Gutenberg's press: Europe begins printing.", zh: "古腾堡印刷机：欧洲开始印刷。" },
      { y: "1453", en: "Constantinople falls to the Ottomans.", zh: "君士坦丁堡陷于奥斯曼。" },
      { y: "1492", en: "Columbus reaches the Caribbean. Reconquista ends.", zh: "哥伦布到达加勒比。再征服战争结束。" },
      { y: "1498", en: "Vasco da Gama reaches India by sea.", zh: "达·伽马由海路抵达印度。" },
    ],
    figures: [
      { en: "Johannes Gutenberg", zh: "约翰内斯·古腾堡" },
      { en: "Leonardo da Vinci", zh: "达·芬奇" },
      { en: "Columbus", zh: "哥伦布" },
      { en: "Zheng He", zh: "郑和" },
      { en: "Mehmed II", zh: "穆罕默德二世" },
    ],
    invented: { en: "European movable type. Trans-Atlantic contact. The painted perspective.", zh: "欧洲活字印刷。跨大西洋接触。透视画法。" },
    ended: { en: "Byzantine Empire. Pre-Columbian isolation of the Americas.", zh: "拜占庭帝国。前哥伦布时代美洲的孤立。" },
    legacy: { en: "Two networks ignite: the printed book and the Atlantic ship.", zh: "两张网络点燃：印刷书与大西洋船。" },
    color: "#d4a85a",
  },
  {
    id: "ce-16",
    label: { en: "16th century", zh: "公元 16 世纪" },
    romanCentury: "XVI",
    yearRange: "1501–1600 CE",
    era: "early-modern",
    theme: { en: "The Reformation", zh: "宗教改革" },
    themeShort: { en: "Luther · Copernicus · Suleiman · silver", zh: "路德 · 哥白尼 · 苏莱曼 · 白银" },
    region: { en: "Germany · Iberia · Ottoman world · Americas · Ming China", zh: "德意志 · 伊比利亚 · 奥斯曼世界 · 美洲 · 大明" },
    body: {
      en: "Luther nails 95 theses to a church door (1517) and shatters Latin Christendom. Copernicus moves the Earth. Suleiman the Magnificent makes the Ottomans a Mediterranean superpower. Spanish silver from Potosí floods the world and reaches Ming China, where it stabilizes the currency. Shakespeare writes Hamlet. Akbar rules Mughal India with religious tolerance. The first global economy is functioning.",
      zh: "路德把九十五条论纲钉在教堂门上（1517），打碎拉丁基督教世界。哥白尼移动了地球。苏莱曼大帝让奥斯曼成为地中海超级大国。波托西的白银涌入世界，进入大明，稳定中国货币。莎士比亚写下《哈姆雷特》。阿克巴以宗教宽容统治莫卧儿印度。第一个全球经济，已经在运转。",
    },
    events: [
      { y: "1517", en: "Luther posts the 95 Theses.", zh: "路德张贴《九十五条论纲》。" },
      { y: "1521", en: "Cortés conquers the Aztec Empire.", zh: "科尔特斯征服阿兹特克帝国。" },
      { y: "1543", en: "Copernicus publishes De revolutionibus.", zh: "哥白尼出版《天体运行论》。" },
      { y: "1545", en: "Spanish discover silver at Potosí.", zh: "西班牙在波托西发现银矿。" },
      { y: "1571", en: "Battle of Lepanto: Ottoman fleet halted.", zh: "勒班陀海战：奥斯曼舰队受挫。" },
      { y: "1600", en: "Shakespeare's Hamlet first performed.", zh: "莎士比亚《哈姆雷特》首次上演。" },
    ],
    figures: [
      { en: "Martin Luther", zh: "马丁·路德" },
      { en: "Suleiman the Magnificent", zh: "苏莱曼大帝" },
      { en: "Copernicus", zh: "哥白尼" },
      { en: "Akbar the Great", zh: "阿克巴大帝" },
      { en: "Shakespeare", zh: "莎士比亚" },
    ],
    invented: { en: "Heliocentrism. Protestant Christianity. The silver-dollar global economy.", zh: "日心说。新教基督教。以白银为本的全球经济。" },
    ended: { en: "A unified Western Christendom. The Aztec and Inca empires.", zh: "统一的西方基督教世界。阿兹特克与印加帝国。" },
    legacy: { en: "The world's first integrated economy and its first religious civil war on a continental scale.", zh: "世界上第一个一体化经济，和大陆规模的第一场宗教内战。" },
    color: "#d4a85a",
  },
  {
    id: "ce-17",
    label: { en: "17th century", zh: "公元 17 世纪" },
    romanCentury: "XVII",
    yearRange: "1601–1700 CE",
    era: "early-modern",
    theme: { en: "The Scientific Revolution", zh: "科学革命" },
    themeShort: { en: "Galileo · Newton · Descartes · joint-stock", zh: "伽利略 · 牛顿 · 笛卡尔 · 股份公司" },
    region: { en: "Europe · Qing China · Mughal India", zh: "欧洲 · 大清 · 莫卧儿印度" },
    body: {
      en: "Galileo points a telescope at the sky and never recants in his heart. Descartes doubts. Newton, in 18 months of plague isolation at Woolsthorpe, invents calculus and gravity. The Dutch East India Company becomes the first joint-stock multinational, with a stock-market valuation that, adjusted, may exceed every modern company combined. The Thirty Years' War kills perhaps a third of the German population. The Treaty of Westphalia (1648) defines the sovereign state.",
      zh: "伽利略将望远镜对准天空，内心从未真正放弃。笛卡尔怀疑。牛顿在沃尔斯索普因瘟疫隔离的十八个月里，发明微积分与万有引力。荷兰东印度公司成为第一家股份制跨国企业 —— 其估值经调整后，可能超过今日所有上市公司之和。三十年战争杀死或许三分之一的德意志人口。《威斯特伐利亚和约》（1648）定义了主权国家。",
    },
    events: [
      { y: "1609", en: "Galileo turns the telescope to the sky.", zh: "伽利略将望远镜对准天空。" },
      { y: "1618", en: "Thirty Years' War begins.", zh: "三十年战争爆发。" },
      { y: "1644", en: "Manchus take Beijing; Qing dynasty begins.", zh: "满洲入主北京；清朝开始。" },
      { y: "1648", en: "Treaty of Westphalia: modern state sovereignty.", zh: "《威斯特伐利亚和约》：现代国家主权确立。" },
      { y: "1687", en: "Newton publishes the Principia.", zh: "牛顿出版《自然哲学的数学原理》。" },
      { y: "1689", en: "English Bill of Rights.", zh: "英国《权利法案》。" },
    ],
    figures: [
      { en: "Galileo Galilei", zh: "伽利略" },
      { en: "Isaac Newton", zh: "牛顿" },
      { en: "René Descartes", zh: "笛卡尔" },
      { en: "Kangxi Emperor", zh: "康熙帝" },
      { en: "Shah Jahan", zh: "沙·贾汗" },
    ],
    invented: { en: "Calculus. Classical physics. The sovereign nation-state. The joint-stock company.", zh: "微积分。经典物理。主权民族国家。股份公司。" },
    ended: { en: "Aristotelian cosmology. Universal religious empire as the European norm.", zh: "亚里士多德宇宙论。作为欧洲规范的普世宗教帝国。" },
    legacy: { en: "Science, sovereignty, and stock — three of the four pillars of modernity.", zh: "科学、主权、股份 —— 现代性四大支柱中的三个。" },
    color: "#d4a85a",
  },
  {
    id: "ce-18",
    label: { en: "18th century", zh: "公元 18 世纪" },
    romanCentury: "XVIII",
    yearRange: "1701–1800 CE",
    era: "early-modern",
    theme: { en: "The Enlightenment", zh: "启蒙运动" },
    themeShort: { en: "Voltaire · 1776 · 1789 · Qianlong", zh: "伏尔泰 · 1776 · 1789 · 乾隆" },
    region: { en: "France · Britain · America · Qing China", zh: "法国 · 英国 · 美洲 · 大清" },
    body: {
      en: "Voltaire, Rousseau, Diderot, and Kant put reason in the dock against king and church. The American Revolution (1776) writes natural rights into a constitution. The French Revolution (1789) tries to refound society on paper and ends in terror, then Napoleon. Britain invents the modern factory. Qianlong rules a peaceful, populous, and confident China that will soon be overtaken. Adam Smith publishes the Wealth of Nations the same year America is declared.",
      zh: "伏尔泰、卢梭、狄德罗、康德 —— 把理性押上被告席，对抗君王与教会。美国革命（1776）将自然权利写入宪法。法国革命（1789）试图凭一纸宪法重造社会，最终走向恐怖，再走向拿破仑。英国发明现代工厂。乾隆统治着一个和平、人口众多、自信的中国 —— 一个即将被超越的中国。亚当·斯密出版《国富论》的同一年，美利坚被宣告。",
    },
    events: [
      { y: "1751", en: "Diderot's Encyclopédie begins publication.", zh: "狄德罗《百科全书》开始出版。" },
      { y: "1769", en: "Watt patents the improved steam engine.", zh: "瓦特申请改良蒸汽机专利。" },
      { y: "1776", en: "American Declaration of Independence. Smith's Wealth of Nations.", zh: "《美国独立宣言》。斯密《国富论》。" },
      { y: "1787", en: "U.S. Constitution drafted.", zh: "美国制宪。" },
      { y: "1789", en: "French Revolution begins.", zh: "法国大革命爆发。" },
      { y: "1799", en: "Napoleon takes power as First Consul.", zh: "拿破仑成为第一执政。" },
    ],
    figures: [
      { en: "Voltaire", zh: "伏尔泰" },
      { en: "Adam Smith", zh: "亚当·斯密" },
      { en: "Thomas Jefferson", zh: "杰斐逊" },
      { en: "Immanuel Kant", zh: "康德" },
      { en: "Qianlong Emperor", zh: "乾隆帝" },
    ],
    invented: { en: "Republics that aspire to last. Free-market economics. The encyclopedia.", zh: "意图长存的共和国。自由市场经济学。百科全书。" },
    ended: { en: "Absolute monarchy as a respectable default.", zh: "作为体面默认值的绝对君主制。" },
    legacy: { en: "The political ideology of every modern country — Left, Right, liberal, conservative — descends from this century.", zh: "今天每个现代国家的政治意识形态 —— 左、右、自由、保守 —— 都源自这个世纪。" },
    color: "#d4a85a",
  },
  {
    id: "ce-19",
    label: { en: "19th century", zh: "公元 19 世纪" },
    romanCentury: "XIX",
    yearRange: "1801–1900 CE",
    era: "modern",
    theme: { en: "The Industrial Revolution", zh: "工业革命" },
    themeShort: { en: "Coal · steel · steam · empire · Darwin", zh: "煤 · 钢 · 蒸汽 · 帝国 · 达尔文" },
    region: { en: "Britain · Europe · Americas · Qing China", zh: "英国 · 欧洲 · 美洲 · 大清" },
    body: {
      en: "In a single century the human energy budget multiplies by orders of magnitude. Coal becomes steam, steam becomes rail, rail becomes empire. The British Empire reaches a quarter of the planet. Darwin publishes On the Origin of Species. Marx publishes Capital. America fights its civil war over slavery and wins itself back. Japan reinvents itself in the Meiji Restoration. Qing China is shattered by the Opium Wars. The world's fastest civilization shift in history.",
      zh: "一个世纪里，人类能源预算扩张数个数量级。煤变成蒸汽，蒸汽变成铁路，铁路变成帝国。大英帝国扩张至地球四分之一。达尔文出版《物种起源》。马克思出版《资本论》。美国为奴隶制打内战并赢回自身。日本以明治维新重塑自我。大清被两次鸦片战争撕开。这是人类史上速度最快的文明轮替。",
    },
    events: [
      { y: "1815", en: "Napoleon defeated at Waterloo.", zh: "拿破仑兵败滑铁卢。" },
      { y: "1839", en: "First Opium War begins.", zh: "第一次鸦片战争爆发。" },
      { y: "1848", en: "Marx publishes the Communist Manifesto. European revolutions.", zh: "马克思《共产党宣言》。欧洲革命之年。" },
      { y: "1859", en: "Darwin publishes On the Origin of Species.", zh: "达尔文《物种起源》。" },
      { y: "1865", en: "U.S. Civil War ends; slavery abolished.", zh: "美国内战结束；废奴。" },
      { y: "1868", en: "Meiji Restoration begins in Japan.", zh: "日本明治维新。" },
      { y: "1879", en: "Edison perfects the lightbulb.", zh: "爱迪生发明实用灯泡。" },
    ],
    figures: [
      { en: "Napoleon Bonaparte", zh: "拿破仑" },
      { en: "Queen Victoria", zh: "维多利亚女王" },
      { en: "Charles Darwin", zh: "达尔文" },
      { en: "Karl Marx", zh: "马克思" },
      { en: "Abraham Lincoln", zh: "林肯" },
      { en: "Emperor Meiji", zh: "明治天皇" },
    ],
    invented: { en: "The factory. Evolution. Electricity at scale. The mass political party.", zh: "工厂。演化论。规模化电力。群众政党。" },
    ended: { en: "Atlantic chattel slavery. Qing self-sufficiency. The pre-industrial economy.", zh: "大西洋黑奴制度。大清的自给。前工业经济。" },
    legacy: { en: "Every chart of GDP, energy, life expectancy bends sharply upward in this one century.", zh: "GDP、能源、人均寿命的图表 —— 都在这一个世纪急剧上扬。" },
    color: "#e8dccc",
  },
  {
    id: "ce-20",
    label: { en: "20th century", zh: "公元 20 世纪" },
    romanCentury: "XX",
    yearRange: "1901–2000 CE",
    era: "modern",
    theme: { en: "Global Conflicts", zh: "全球冲突" },
    themeShort: { en: "Two world wars · the bomb · the moon · the web", zh: "两次世界大战 · 原子弹 · 登月 · 互联网" },
    region: { en: "Worldwide", zh: "全球" },
    body: {
      en: "Two world wars kill perhaps 100 million people and remake the map. The atom is split (1945). Humans walk on the Moon (1969). DNA is decoded (1953). The Soviet Union rises and falls. China returns from its 'century of humiliation' to become a manufacturing superpower. The internet is born. By century's end, more people are alive than have ever previously died.",
      zh: "两次世界大战夺走或许一亿人命，重画地图。原子在 1945 年被分裂。人类在 1969 年登月。DNA 在 1953 年被解码。苏联崛起又陨落。中国从『百年屈辱』归来，成为制造业超级大国。互联网诞生。世纪末，活着的人比此前所有时代死去的人还要多。",
    },
    events: [
      { y: "1914", en: "World War I begins.", zh: "第一次世界大战爆发。" },
      { y: "1917", en: "Russian Revolution.", zh: "俄国革命。" },
      { y: "1939", en: "World War II begins.", zh: "第二次世界大战爆发。" },
      { y: "1945", en: "Atomic bombs end WWII. UN founded.", zh: "原子弹终结二战。联合国成立。" },
      { y: "1949", en: "People's Republic of China founded.", zh: "中华人民共和国成立。" },
      { y: "1969", en: "Apollo 11 lands on the Moon.", zh: "阿波罗 11 号登月。" },
      { y: "1989", en: "Berlin Wall falls. Web invented at CERN.", zh: "柏林墙倒塌。万维网在 CERN 诞生。" },
      { y: "2001", en: "(prelude) Human Genome Project completes draft.", zh: "（前奏）人类基因组草图完成。" },
    ],
    figures: [
      { en: "Albert Einstein", zh: "爱因斯坦" },
      { en: "Mao Zedong", zh: "毛泽东" },
      { en: "FDR · Churchill · Stalin", zh: "罗斯福 · 丘吉尔 · 斯大林" },
      { en: "Mahatma Gandhi", zh: "甘地" },
      { en: "Watson · Crick · Franklin", zh: "沃森 · 克里克 · 富兰克林" },
      { en: "Deng Xiaoping", zh: "邓小平" },
    ],
    invented: { en: "The atomic bomb. Antibiotics. The computer. The internet. DNA decoded.", zh: "原子弹。抗生素。计算机。互联网。DNA 解码。" },
    ended: { en: "European empire. Apartheid. Smallpox.", zh: "欧洲帝国体系。种族隔离制度。天花。" },
    legacy: { en: "The most violent and the most prosperous century in human history — at the same time.", zh: "人类历史上最暴力、也最繁荣的世纪 —— 同时。" },
    color: "#e8dccc",
  },
  {
    id: "ce-21",
    label: { en: "21st century", zh: "公元 21 世纪" },
    romanCentury: "XXI",
    yearRange: "2001–present",
    era: "modern",
    theme: { en: "The Information Age", zh: "信息时代" },
    themeShort: { en: "Smartphone · AI · climate · multipolar world", zh: "智能手机 · AI · 气候 · 多极世界" },
    region: { en: "Worldwide", zh: "全球" },
    body: {
      en: "A quarter into the century, most adults carry a supercomputer in their pocket and outsource cognition to large language models. China's GDP is approaching the U.S.'s. CRISPR edits genes for sickle cell. Photovoltaic and battery costs fall by 99%. A coronavirus kills millions. Atmospheric CO₂ passes 420 ppm. Generative AI arrives. The defining theme is not yet decided — that is what the people alive today are choosing.",
      zh: "进入本世纪四分之一时，大多数成年人口袋里装着一台超级计算机，并把认知外包给大语言模型。中国 GDP 接近美国。CRISPR 编辑基因治疗镰刀型贫血。光伏与电池成本下降 99%。一场冠状病毒夺走数百万生命。大气中 CO₂ 越过 420 ppm。生成式 AI 到来。这个世纪的主题尚未确定 —— 它正在被今天活着的人选择。",
    },
    events: [
      { y: "2001", en: "September 11. War on Terror.", zh: "九一一事件。反恐战争。" },
      { y: "2007", en: "iPhone launches. Mobile internet for everyone.", zh: "iPhone 发布。移动互联网普及。" },
      { y: "2008", en: "Global Financial Crisis. Bitcoin whitepaper.", zh: "全球金融危机。比特币白皮书发布。" },
      { y: "2020", en: "COVID-19 pandemic.", zh: "新冠疫情。" },
      { y: "2022", en: "ChatGPT launches. Generative AI reaches one billion.", zh: "ChatGPT 发布。生成式 AI 进入十亿用户。" },
      { y: "2023", en: "First CRISPR therapy approved (sickle cell).", zh: "首个 CRISPR 疗法获批（镰状细胞病）。" },
      { y: "2025+", en: "Open: AGI · climate adaptation · multipolarity.", zh: "未定：AGI · 气候适应 · 多极世界。" },
    ],
    figures: [
      { en: "Steve Jobs", zh: "乔布斯" },
      { en: "Xi Jinping", zh: "习近平" },
      { en: "Greta Thunberg", zh: "格蕾塔·通贝里" },
      { en: "Geoffrey Hinton", zh: "辛顿" },
      { en: "Satoshi Nakamoto", zh: "中本聪" },
      { en: "Jennifer Doudna", zh: "詹妮弗·杜德娜" },
    ],
    invented: { en: "The smartphone. Cryptocurrency. Generative AI. CRISPR therapy.", zh: "智能手机。加密货币。生成式 AI。CRISPR 疗法。" },
    ended: { en: "Single-superpower geopolitics. Stable Holocene climate.", zh: "单一超级大国的地缘格局。稳定的全新世气候。" },
    legacy: { en: "Undecided. You are inside the sentence that will be written by future centuries.", zh: "未定。你身处一句话之内，它将被未来的世纪写下。" },
    color: "#e8dccc",
  },
];

export const HERO = {
  pre: { en: "Three thousand years · one century at a time", zh: "三千年 · 一世纪一站" },
  title: { en: "The Centuries", zh: "世纪志" },
  subtitle: { en: "An Atlas of Civilization, 1000 BCE → Now", zh: "公元前一千年 → 现在 · 一部文明地图" },
  lede: {
    en: "From David's Kingdom to the Information Age, every century has a defining theme — a force that pulled the rest of the world along with it. This is a long-form, bilingual atlas of those thirty-one chapters: what each one invented, what it ended, and what we still owe to it.",
    zh: "从大卫王朝到信息时代，每一个世纪都有一种主导主题 —— 一股拉动整个世界的力量。本站是这三十一个章节的中英双语长读地图：每一个世纪发明了什么、终结了什么、又给我们留下了什么。",
  },
  ctaPrimary: { en: "Open the Timeline", zh: "打开时间线" },
  ctaSecondary: { en: "Read the Thesis", zh: "阅读论纲" },
};

export const THESIS = {
  title: { en: "A century is the unit at which civilization remembers itself.", zh: "世纪，是文明记得自己的最小单位。" },
  body: {
    en: "A year is too short — a lifetime can fit inside one. A millennium is too long — no human ever lives one. A century is the unit at which entire generations are born, fight, build, lose, and pass on. Each row of this table is one century's verdict: the single theme that, with the benefit of distance, comes to stand for everything that happened. The verdicts are deliberately reductive — they are headlines, not encyclopedias. Their job is to make three thousand years legible at one glance, and then send you down into the detail when something catches.",
    zh: "一年太短 —— 一生可以放进一年。一千年太长 —— 没人活过千年。世纪，是整代人出生、争斗、建造、失败、传承的单位。本表每一行，是一个世纪的判词：当时距足够远，那个能代表一切的单一主题。这些判词是刻意简化的 —— 是标题，不是百科。它们的任务，是让三千年在一眼之中可读，然后把你引向细节。",
  },
};

export const PATTERNS = {
  title: { en: "What Repeats", zh: "重复了什么" },
  items: [
    {
      title: { en: "Empires after plagues", zh: "瘟疫之后的帝国" },
      body: {
        en: "Antonine plague → 3rd-century crisis. Justinian plague → loss of the Mediterranean. Black Death → Renaissance. COVID → ?",
        zh: "安东尼瘟疫 → 三世纪危机。查士丁尼瘟疫 → 失去地中海。黑死病 → 文艺复兴。新冠 → ？",
      },
    },
    {
      title: { en: "Translation as ignition", zh: "翻译，作为引信" },
      body: {
        en: "Greek to Arabic (Baghdad, 9th c.). Arabic to Latin (Toledo, 12th c.). Greek back to Italian (Florence, 15th c.). Every translation wave is a renaissance wave.",
        zh: "希腊→阿拉伯（巴格达，9 世纪）。阿拉伯→拉丁（托莱多，12 世纪）。希腊→意大利（佛罗伦萨，15 世纪）。每一次翻译浪潮，都是一次复兴浪潮。",
      },
    },
    {
      title: { en: "Print, twice", zh: "印刷，发生过两次" },
      body: {
        en: "Bi Sheng's movable type (11th c., China) preserved knowledge inside its civilization. Gutenberg's press (15th c., Europe) blew its civilization open. Same invention; opposite trajectories.",
        zh: "毕昇活字（11 世纪，中国）把知识保存在自身文明内部。古腾堡印刷（15 世纪，欧洲）把自己的文明炸开。同一个发明，相反的轨迹。",
      },
    },
    {
      title: { en: "Capitals shift east, west, east, west", zh: "首都，东、西、东、西" },
      body: {
        en: "Babylon → Athens → Rome → Constantinople → Baghdad → Cordoba → Florence → Paris → London → New York → ?",
        zh: "巴比伦 → 雅典 → 罗马 → 君士坦丁堡 → 巴格达 → 科尔多瓦 → 佛罗伦萨 → 巴黎 → 伦敦 → 纽约 → ？",
      },
    },
    {
      title: { en: "The pendulum: open → closed → open", zh: "钟摆：开 → 闭 → 开" },
      body: {
        en: "Han China (open) → 3 Kingdoms (closed) → Tang (open) → late Ming (closed) → Qing (closed). Each closure costs a civilization a century or two of relative decline.",
        zh: "汉朝（开）→ 三国（闭）→ 唐朝（开）→ 明末（闭）→ 清朝（闭）。每一次闭关，都让一个文明付出一两个世纪的相对衰落。",
      },
    },
    {
      title: { en: "The four pillars of modernity, set 17th c.", zh: "现代性的四根柱子，在 17 世纪立起" },
      body: {
        en: "Science (Newton). Sovereignty (Westphalia). Stock (Dutch VOC). Suffrage (English Bill of Rights). Every modern country is some weighted blend of those four.",
        zh: "科学（牛顿）。主权（威斯特伐利亚）。股份（荷兰东印度）。选举（英国《权利法案》）。每个现代国家，都是这四者的一组加权混合。",
      },
    },
  ],
};

export const CLOSING = {
  title: {
    en: "If the theme of the 20th century was global conflict, what is the theme of the 21st?",
    zh: "若 20 世纪的主题是全球冲突，那 21 世纪的主题，将是什么？",
  },
  body: {
    en: "The honest answer is that we do not know yet — not because no candidates exist, but because too many do. The information age. The climate transition. The end of unipolarity. The arrival of non-human intelligence. The aging of the developed world. In every previous century on this table, the theme is named after the fact. The work of being alive in the 21st century is being one of the people who decides which name sticks.",
    zh: "诚实的答案是：还不知道 —— 不是因为没有候选，而是因为候选太多。信息时代。气候转型。单极秩序终结。非人智能登场。发达世界老龄化。本表此前每一个世纪的主题，都是事后命名。生活在 21 世纪的人，正承担着决定哪一个名字会留下的工作。",
  },
};

export const META = {
  siteName: { en: "The Centuries", zh: "世纪志" },
  description: {
    en: "Three thousand years of civilization, one century at a time. A bilingual long-read atlas: what each century invented, ended, and bequeathed — from David's kingdom to the Information Age.",
    zh: "三千年文明，一世纪一站。中英双语长读地图：每一个世纪发明了什么、终结了什么、留下了什么 —— 从大卫王朝到信息时代。",
  },
};
